name: molecular_docking_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - rdkit
  - openbabel
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - tqdm
  - requests
  - pyyaml
  - gemmi
  - cairosvg
  - ipywidgets
  - notebook
  - pip
  - pip:
      - plip
      - biopython
      - py3Dmol

