paths:
  receptors_folder: "data/receptors"
  native_ligands_folder: "data/native_ligands"
  ligands_folder: "data/ligands"
  output_folder: "data/output"
  crystals_folder: "data/crystals"
  temp_dir: "tmp"
  smina_path: "/usr/local/bin/smina"



runtime:
  n_jobs: 8              # parallel processes
  keep_tmp: false

# ───── Docking mode ─────
#  full_matrix     – every ligand vs every receptor
#  diagonal        – only matching rows in complexes.csv (R_i ↔ L_i)
#  redock_native   – only native ligands (validation)
docking_mode: "full_matrix"


engine: "smina"

# gridbox default kept but ignored when .box.json exists        # vina / gnina easy to add later

# global defaults (can be overridden per‑receptor by gridbox_generator)
docking_params:
  exhaustiveness: 32
  num_modes: 10
  cpu: 4
  autobox_add: 4.0       # Å margin
  center: [0.0, 0.0, 0.0]
  size:   [20.0, 20.0, 20.0]

postprocess:
  native_margin: 0.5     # kcal/mol – score must be < native − margin