
paths:
  receptors_folder: "data/receptors"
  receptors_cleaned_folder: "data/receptors_cleaned"
  native_ligands_folder: "data/native_ligands"
  ligands_folder: "data/ligands"
  output_folder: "data/output"
  crystals_folder: "data/crystals"
  temp_dir: "tmp"
  smina_path: "/usr/local/bin/smina"

runtime:
  n_jobs: 1          # parallel processes
  keep_tmp: false

# ───── Docking mode ─────
#  full_matrix     – every ligand vs every receptor
#  diagonal        – only matching rows in complexes.csv (R_i ↔ L_i)
#  redock_native   – only native ligands (validation)
docking_mode: "redock_native"


engine: "smina"

# gridbox default kept but ignored when .box.json exists        # vina / gnina easy to add later

# global defaults (can be overridden per‑receptor by gridbox_generator)
docking_params:
  exhaustiveness: 8
  num_modes: 10
  cpu: 1
  autobox_add: 4.0       # Å margin
  center: [0.0, 0.0, 0.0]
  size:   [20.0, 20.0, 20.0]

fetch_crystals:
  enabled: true
  pdb_ids: ["1M17"]
  ligand_resnames:
    1M17: "AQ4"

ligand_csv:
  enabled: false          # set true when you have a CSV
  file: "my_ligands.csv"
  smiles_column: "SMILES"
  id_column: "ID"

postprocess:
  native_margin: 0.5
  top_n: 20