name: docking
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12
  - rdkit
  - pdbfixer
  - pandas
  - pyyaml
  - tqdm
  - matplotlib
  - scikit-learn
  - requests
  - pip
  - pip:
      - AutoDockTools_py3